# Generated by Django 3.2.9 on 2022-10-08 12:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='Io', max_length=100, verbose_name='Имя'),
        ),
    ]
