# Generated by Django 3.2.9 on 2022-10-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('platform', models.TextField(verbose_name='Платформа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('add_information', models.TextField(blank=True, verbose_name='Дополнительное описание')),
                ('goals', models.TextField(verbose_name='Цели')),
                ('equipment', models.TextField(verbose_name='Оборудование')),
                ('theme', models.TextField(verbose_name='Тема')),
                ('date', models.TextField(verbose_name='Дата')),
                ('time', models.TextField(verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
