# Generated by Django 3.2.9 on 2022-10-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.TextField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='equipment',
            field=models.TextField(verbose_name='Оборудование'),
        ),
        migrations.AlterField(
            model_name='event',
            name='goals',
            field=models.TextField(verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='city',
            field=models.TextField(verbose_name='Город'),
        ),
    ]
