# Generated by Django 3.2.9 on 2022-10-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20221009_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TextField(default='12:12:12', verbose_name='Время'),
        ),
    ]
