# Generated by Django 3.2.16 on 2022-10-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20221029_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='add_information',
            field=models.TextField(verbose_name='Дополнительное описание'),
        ),
    ]
