# Generated by Django 3.2.9 on 2022-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TextField(verbose_name='Время'),
        ),
    ]
