# Generated by Django 3.2.9 on 2022-10-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='add_information',
            field=models.TextField(default='drf', verbose_name='Дополнительное описание'),
        ),
    ]
