# Generated by Django 3.2.9 on 2022-10-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_add_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='add_information',
            field=models.TextField(verbose_name='Дополнительное описание'),
        ),
    ]
