# Generated by Django 3.2.9 on 2022-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_add_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='add_information',
            field=models.TextField(blank=True, verbose_name='Дополнительное описание'),
        ),
    ]
