# Generated by Django 3.2.9 on 2022-10-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_add_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='platform',
            field=models.TextField(verbose_name='Платформа'),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
