# Generated by Django 3.2.9 on 2022-10-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Название программы')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True, verbose_name='Стадия разработки')),
            ],
            options={
                'verbose_name': 'Стадия разработки',
                'verbose_name_plural': 'Стадии разработки',
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, verbose_name='Название')),
                ('website', models.CharField(max_length=500, verbose_name='Сайт стартапа')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание стартапа')),
                ('presentation', models.CharField(max_length=500, verbose_name='Презентация')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.program', verbose_name='Программа')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.stage', verbose_name='Стадия разработки')),
            ],
            options={
                'verbose_name': 'Стартап',
                'verbose_name_plural': 'Стартапы',
            },
        ),
    ]
