# Generated by Django 3.2.9 on 2022-10-08 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='application_plan',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='stage',
        ),
        migrations.DeleteModel(
            name='ApplicationProgram',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Startup',
        ),
    ]
