# Generated by Django 3.2.9 on 2022-10-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_alter_startup_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationProgram',
            new_name='Program',
        ),
        migrations.RenameField(
            model_name='startup',
            old_name='application_program',
            new_name='program',
        ),
    ]
