# Generated by Django 3.2.9 on 2022-10-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_auto_20221009_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=75, unique=True, verbose_name='Стадия разработки'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='Описание стартапа'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.CharField(max_length=500, verbose_name='Сайт стартапа'),
        ),
    ]
