# Generated by Django 3.2.9 on 2022-10-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_auto_20221009_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='presentation',
            field=models.CharField(default='1', max_length=500, verbose_name='Презентация'),
        ),
    ]
